server:
  port: 10037
logging:
  level:
    top.keiskeiframework: debug
#    org.springframework: debug
#    jdbc: error
  pattern:
    file: "%d [%X{userName}-%X{userId}] %-5level - %msg%n"
    console: "%d [%X{userName}-%X{userId}] [%thread] %-5level %logger{36} %line - %msg%n"
spring:
  jackson:
    default-property-inclusion: non_null
  messages:
    basename: i18n/messages
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: WEB-INF/**
  freemarker:
    cache: false
  cache:
    type: simple
  data:
    mongodb:
      database: ${MONGO_DATABASE:dw_aminer1}
      port: ${MONGO_PORT:27017}
      host: ${MONGO_HOST:127.0.0.1}
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
  datasource:
    name: dw_aminer
  mail:
    host: ${EMAIL_HOST}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    port: ${EMAIL_PORT}
    test-connection: true
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
keiskei:
  system:
    permit-uri: /swagger-ui.html,/images/**,/webjars/**,/v2/**,/configuration/**,/csrf,/doc.html,/webjars/**,/swagger-resources/**,/favicon.ico
    maximum-sessions: 1
  cross: true





