server:
  port: 10037
  servlet:
    session:
      timeout: P60D
      cookie:
        http-only: false
logging:
  level:
    top.keiskeiframework: debug
#    org.springframework: debug
#    jdbc: error
  pattern:
    file: "%d [%X{mdcTraceId}] [%thread] %-5level - %msg%n"
    console: "%d [%X{mdcTraceId}] [%thread] %-5level %logger{36} %line - %msg%n"
spring:
  session:
    store-type: mongodb
  jackson:
    default-property-inclusion: non_null
  messages:
    basename: i18n/messages
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: WEB-INF/**
  freemarker:
    cache: false
  cache:
    type:
  data:
    mongodb:
      database: dw_aminer1
      port: 27017
      host: 127.0.0.1
keiskei:
  cache-expired:
    FILE_MINUTE:
  system:
    permit-uri: /swagger-ui.html,/images/**,/webjars/**,/v2/**,/configuration/**,/csrf,/doc.html,/webjars/**,/swagger-resources/**,/favicon.ico
    cross: true
    maximum-sessions: 1
  generate:
    base-path: /Users/cjm/IdeaProjects/items/user/
    base-admin-path: /Users/cjm/WebstormProjects/keiskei-admin-template/
    base-front-path: /Users/cjm/IdeaProjects/items/front/



