server:
  port: ${SERVER_PORT:10037}
  servlet:
    session:
      timeout: P60D
      cookie:
        http-only: false
logging:
  level:
    top.keiskeiframework: debug
  #    jdbc: error
  pattern:
    file: "%d [%X{userName}-%X{userId}] %-5level - %msg%n"
    console: "%d [%X{userName}-%X{userId}] [%thread] %-5level %logger{36} %line - %msg%n"
spring:
  session:
    store-type: redis
  jackson:
    default-property-inclusion: non_null
  messages:
    basename: i18n/messages
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  data:
    mongodb:
      database: ${MONGO_DATABASE:test_demo}
      port: ${MONGO_PORT:27017}
      host: ${MONGO_HOST:127.0.0.1}
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
  datasource:
    name: test_demo
  redis:
    timeout: 60000
    password: ${REDIS_PASSWORD:123456}
    database: ${REDIS_DB:0}
    port: ${REDIS_PORT:6379}
    host: ${REDIS_HOST:localhost}
  freemarker:
    cache: false
management:
  endpoints:
    web:
      exposure:
        include: 'prometheus'
  metrics:
    tags:
      application: ${spring.application.name}
keiskei:
  system:
    permit-uri: /swagger-ui.html,/images/**,/webjars/**,/v2/**,/configuration/**,/csrf,/doc.html,/webjars/**,/swagger-resources/**,/favicon.ico
    cross: true
    maximum-sessions: 1
  generate:
    base-path: D:/tmp/file/item/
    base-admin-path: C:/Users/CJM/item/keiskei-admin-template/
    base-front-path: /Users/cjm/IdeaProjects/items/front/
  file:
    local:
      url-suffix: http://127.0.0.1:7999/admin/v2/common/file/show/
