logging:
  level:
    top.keiskeiframework: debug
    jdbc: error
  pattern:
    file: "%d [%X{userName}-%X{userId}] %-5level - %msg%n"
    console: "%d [%X{userName}-%X{userId}] [%thread] %-5level %logger{36} %line - %msg%n"
spring:
  session:
    store-type: redis
  jackson:
    default-property-inclusion: non_null
  messages:
    basename: i18n/messages
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  datasource:
    name: test_demo
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Cjm@12070817
    url: jdbc:mysql://127.0.0.1:3306/test_demo?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
  redis:
    timeout: 6000
    password: 123456
    database: 11
    port: 6379
    host: 127.0.0.1
mybatis-plus:
  type-enums-package: top.keiskeiframwork.**
  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
#  global-config:
#    db-config:
#      logic-delete-field: d # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
#      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
#      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)