server:
  port: 8002
spring:
  application:
    name: goods-service
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        username: nacos
        password: nacos
        namespace: public