spring:
  profiles:
    active: ${ACTIVE_PROFILE:@environment@}
  application:
    name: ${APPLICATION_NAME:cpreading-reader}
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        username: nacos
        password: nacos
        namespace: public




